-- Seed the alerts feed. Run after supabase-schema.sql. These are example items —
-- in production this table is fed by your newsroom. Sober, education-framed.

insert into content_items (title, body, category, states, min_age) values
('Gift-card scam targeting Social Security recipients',
 'Callers claiming to be from "Social Security" are demanding payment in gift cards to avoid a suspended benefit. The SSA never asks for gift cards and never threatens immediate arrest. Hang up and report it at oig.ssa.gov.',
 'scam', '{}', 62),
('Medicare impostor calls rise before Open Enrollment',
 'Scammers pose as Medicare to "verify" your number or sell a plan. Medicare does not cold-call to sell you anything. Never give your Medicare number to an unsolicited caller.',
 'scam', '{}', 63),
('Grandparent scam: the urgent "I''m in trouble" call',
 'A caller imitates a grandchild in a crisis and begs for secret, immediate money. Verify by calling the family member directly on a known number before doing anything.',
 'scam', '{}', 60),
('Bank impersonation texts asking you to "confirm" a charge',
 'A text claims a suspicious charge and links you to a fake login. Your bank will not text you a link to sign in. Go to the bank''s app or call the number on your card.',
 'scam', '{}', 0),
('2026 Social Security COLA: what it means in your check',
 'The annual cost-of-living adjustment changes your monthly benefit. Check your December statement for your exact new amount and update your budget.',
 'benefit', '{}', 62),
('Medicare Open Enrollment runs Oct 15 – Dec 7',
 'Plans change their costs and drug coverage every year. Re-shop your plan during this window even if you''re happy — last year''s best plan may not be this year''s.',
 'benefit', '{}', 63),
('Are you leaving the Saver''s Credit or other benefits unclaimed?',
 'Millions miss benefits they qualify for. Check BenefitsCheckUp.org for programs in your area covering medical, food, and utility costs.',
 'benefit', '{}', 60),
('Extra Help with Medicare drug costs',
 'If your income is limited, the Extra Help program can sharply cut what you pay for prescriptions. Apply through the SSA — it''s free to apply.',
 'benefit', '{}', 64),
('Grocery prices: where costs rose most this month',
 'Track your own basket. Staples like eggs, beef, and coffee move at different rates — knowing which rose helps you adjust before it strains your budget.',
 'inflation', '{}', 0),
('Medicare Part B premium change for the new year',
 'The standard Part B premium is adjusted yearly and comes straight out of your Social Security check. Confirm your new net deposit.',
 'inflation', '{}', 63),
('Home and auto insurance premiums keep climbing',
 'Premiums for older homeowners have risen sharply. Re-shop annually and ask about senior, bundling, and low-mileage discounts.',
 'inflation', '{}', 0),
('Property-tax relief for seniors in Texas',
 'Texas offers a homestead exemption and a school-tax ceiling for homeowners 65+. Apply through your county appraisal district — it can cut your bill meaningfully.',
 'costofliving', '{TX}', 65),
('Florida''s additional homestead exemption for seniors',
 'Some Florida counties offer an extra homestead exemption for residents 65+ below an income limit. Check with your county property appraiser.',
 'costofliving', '{FL}', 65),
('California property-tax postponement for seniors',
 'California''s Property Tax Postponement program lets eligible homeowners 62+ defer property taxes on their primary residence. Applications open annually.',
 'costofliving', '{CA}', 62),
('New York''s Enhanced STAR for seniors',
 'Homeowners 65+ under the income limit can get the Enhanced STAR property-tax exemption. Re-verify income each year to keep it.',
 'costofliving', '{NY}', 65),
('LIHEAP can help with heating and cooling bills',
 'The Low Income Home Energy Assistance Program helps cover utility costs. Funds are limited and seasonal — apply early through your state.',
 'costofliving', '{}', 0);
